kind: pipeline
type: docker
name: httpd-image-build

# Trigger conditions
trigger:
  branch:
    - '2.4'
    - main
  event:
    - custom
    - push
    - pull_request

# Pipeline steps
steps:
  # Build image
  - name: docker-build
    image: plugins/docker
    when:
      branch:
        - '2.4'
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/httpd
      tags:
        - latest
        - 2.4.62
        - 2.4.62-${DRONE_COMMIT:0:8}-drone-build-${DRONE_BUILD_NUMBER}

  # Test image
  - name: docker-test
    image: kernel528/httpd:latest
    when:
      branch:
        - main
    commands:
      - cat /etc/alpine-release
      - "httpd -v"

  # Slack notification
  - name: notify
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
    when:
      status:
        - failure
        - success