kind: pipeline
type: docker
name: httpd-arm64

trigger:
  branch:
    - '2.4-arm64'
  event:
    - pull_request

# Build the docker image for arm64 architecture
steps:
  - name: setup-qemu
    image: multiarch/qemu-user-static
    privileged: true
    commands:
      - /bin/qemu-system-arm --version

  - name: httpd-image-build-arm64
    image: plugins/docker
    environment:
      DOCKER_BUILDKIT: 1
    settings:
      platforms:
        - linux/arm64
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/httpd
      tags:
        - latest-arm64
        - '2.4-arm64'
        - '2.4-drone-build-${DRONE_BUILD_NUMBER}-arm64'
        - '2.4.62-arm64'
        - '2.4.62-drone-build-${DRONE_BUILD_NUMBER}-arm64'

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts
---

kind: pipeline
type: docker
name: main-httpd-arm64

trigger:
  event:
    - push
    - tag
  branch:
    - main-arm64

# Build the docker image for the main branch & tagged release
steps:
  - name: setup-qemu
    image: multiarch/qemu-user-static
    privileged: true
    commands:
      - /bin/qemu-system-arm --version

  - name: main-docker-image-build
    image: plugins/docker
    when:
      event:
        - tag
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kernel528/httpd
      tags:
        - ${DRONE_TAG}

  # Test docker image
  - name: latest-httpd-arm64-test
    image: kernel528/httpd:latest-arm64
    when:
      branch:
        - main-arm64
      event:
        - push
    commands:
      - cat /etc/alpine-release
      - httpd -v

  # Slack notification
  - name: slack-notification
    image: plugins/slack
    when:
      status:
        - failure
        - success
    settings:
      webhook:
        from_secret: slack_webhook_drone_alerts